# version: '4.29'

# services:
#   catalogdb:
#     image: postgres:14-alpine

version: '3.9'

services:
  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basketdb:
    image: postgres

  basketdistributedcache:
    image: redis


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:  



